baseURL = 'https://tech-knowledge-notes.netlify.app/'
languageCode = 'en-us'
title = 'My Tech Knowledge Notes'
theme = "PaperMod"
[params]
  author = "Ankur Singh"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = false
  ShowWordCount = false
  defaultTheme = "auto"
  ShowPostMeta = true
  disableSpecial1stPost = true
  mainSections = ["notes"]
  showDate = false
  showAuthor = false
  showReadingTime = false
  sidebarHideSections = false  # show section folders
  sidebarHidePages = false     # show pages in sidebar

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

# Networking topic
[[menu.main]]
name = "Networking"
url = "/networking/"
identifier = "networking"
weight = 10

# System Design topic
[[menu.main]]
name = "System design"
url = "/systemdesign/cdn/"
parent = "systemdesign"
weight = 5